"""Curated, cited clinical corpus — the grounding source for retrieval.

Scoped ruthlessly to the pediatric ARI / pneumonia golden path plus the drugs in
the demo. Each entry is one atomic clinical unit (a rule, a step, a monograph)
with its source + section so every retrieved fact carries a citation. A small,
flawless corpus beats a broad, noisy one.
"""

CORPUS = [
    # ---------------------------------------------------------------- WHO IMCI
    {
        "id": "imci-assess",
        "source": "WHO IMCI chart booklet",
        "section": "Cough or difficult breathing — Assess",
        "ref": "Assess the sick child",
        "lang": "en",
        "text": "For a child with cough or difficult breathing, count the breaths in one minute, look for lower chest-wall indrawing, and look and listen for stridor in a calm child.",
        "tags": ["cough", "difficult breathing", "respiratory rate", "count breaths", "chest indrawing", "stridor", "assess", "child"],
    },
    {
        "id": "imci-threshold",
        "source": "WHO IMCI chart booklet",
        "section": "Fast breathing thresholds",
        "ref": "Fast breathing for age",
        "lang": "en",
        "text": "Fast breathing for age: a child 2 to 11 months breathes 50 breaths per minute or more; a child 12 months up to 5 years breathes 40 breaths per minute or more.",
        "tags": ["fast breathing", "tachypnea", "respiratory rate", "threshold", "age", "50", "40", "breaths per minute"],
    },
    {
        "id": "imci-severe",
        "source": "WHO IMCI chart booklet",
        "section": "Classify — Severe pneumonia or very severe disease",
        "ref": "Severe pneumonia / very severe disease",
        "lang": "en",
        "text": "A child with cough or difficult breathing who has any general danger sign, or lower chest-wall indrawing, or stridor in a calm child is classified as SEVERE PNEUMONIA OR VERY SEVERE DISEASE: give the first dose of an appropriate antibiotic and refer URGENTLY to hospital.",
        "tags": ["severe pneumonia", "very severe disease", "chest indrawing", "stridor", "danger sign", "refer urgently", "hospital", "classify"],
    },
    {
        "id": "imci-pneumonia",
        "source": "WHO IMCI chart booklet",
        "section": "Classify — Pneumonia",
        "ref": "Pneumonia",
        "lang": "en",
        "text": "A child with fast breathing but no general danger sign, no chest indrawing and no stridor is classified as PNEUMONIA: give an oral antibiotic, soothe the throat, advise the mother on home care, and follow up in 3 days.",
        "tags": ["pneumonia", "fast breathing", "oral antibiotic", "home care", "follow up", "classify"],
    },
    {
        "id": "imci-nopneumonia",
        "source": "WHO IMCI chart booklet",
        "section": "Classify — No pneumonia: cough or cold",
        "ref": "No pneumonia (cough or cold)",
        "lang": "en",
        "text": "A child with cough or cold and no fast breathing and no danger signs has NO PNEUMONIA: no antibiotic, soothe the throat and relieve the cough with a safe remedy, and advise when to return.",
        "tags": ["no pneumonia", "cough", "cold", "no antibiotic", "home care", "classify"],
    },
    {
        "id": "imci-danger",
        "source": "WHO IMCI chart booklet",
        "section": "General danger signs",
        "ref": "General danger signs",
        "lang": "en",
        "text": "General danger signs in a sick child: not able to drink or breastfeed, vomits everything, has had convulsions, or is lethargic or unconscious. Any general danger sign means urgent referral.",
        "tags": ["general danger sign", "not able to drink", "vomits everything", "convulsions", "lethargic", "unconscious", "urgent referral"],
    },
    {
        "id": "imci-return-bn",
        "source": "WHO IMCI chart booklet",
        "section": "When to return immediately (counselling)",
        "ref": "Return-immediately advice",
        "lang": "bn",
        "text": "শিশুকে সাথে সাথে হাসপাতালে ফিরিয়ে আনুন যদি: শ্বাস নিতে কষ্ট হয়, দ্রুত শ্বাস নেয়, বুক টেনে শ্বাস নেয়, কিছু খেতে বা পান করতে না পারে, খিঁচুনি হয়, অথবা শিশু আরও অসুস্থ হয়ে পড়ে।",
        "tags": ["return immediately", "danger signs", "শ্বাস", "খিঁচুনি", "বিপদ", "bangla"],
    },
    # ----------------------------------------------- DGHS Standard Treatment Guidelines
    {
        "id": "stg-pneumonia-firstline",
        "source": "DGHS Standard Treatment Guidelines (Bangladesh)",
        "section": "Childhood pneumonia — treatment",
        "ref": "First-line antibiotic",
        "lang": "en",
        "text": "First-line oral antibiotic for non-severe childhood pneumonia is amoxicillin, dosed by body weight for a full course; review at 3 days.",
        "tags": ["pneumonia", "amoxicillin", "first line", "antibiotic", "dose", "children", "treatment"],
    },
    {
        "id": "stg-severe-referral",
        "source": "DGHS Standard Treatment Guidelines (Bangladesh)",
        "section": "Severe pneumonia — referral",
        "ref": "Severe pneumonia management",
        "lang": "en",
        "text": "Severe pneumonia in a child requires urgent referral; give the first pre-referral antibiotic dose and do not attempt definitive management at the primary level.",
        "tags": ["severe pneumonia", "referral", "pre-referral antibiotic", "primary care", "children"],
    },
    {
        "id": "stg-supportive",
        "source": "DGHS Standard Treatment Guidelines (Bangladesh)",
        "section": "ARI — supportive care",
        "ref": "Supportive care",
        "lang": "en",
        "text": "Supportive care for acute respiratory infection: continue feeding and fluids, clear a blocked nose, give paracetamol for high fever, and avoid cough syrups in young children.",
        "tags": ["supportive care", "feeding", "fluids", "paracetamol", "fever", "ARI", "cough syrup"],
    },
    # ------------------------------------------------------- National Drug Formulary
    {
        "id": "nf-amoxicillin",
        "source": "National Drug Formulary (BD) / BNF",
        "section": "Amoxicillin",
        "ref": "Amoxicillin — penicillin",
        "lang": "en",
        "text": "Amoxicillin is a penicillin-class antibiotic. It is CONTRAINDICATED in patients with penicillin hypersensitivity. Indications include pneumonia, otitis media and urinary tract infection.",
        "tags": ["amoxicillin", "penicillin", "contraindicated", "hypersensitivity", "allergy", "antibiotic", "monograph"],
    },
    {
        "id": "nf-azithromycin",
        "source": "National Drug Formulary (BD) / BNF",
        "section": "Azithromycin",
        "ref": "Azithromycin — macrolide",
        "lang": "en",
        "text": "Azithromycin is a macrolide antibiotic and is a suitable alternative when a penicillin is contraindicated, for example in penicillin allergy.",
        "tags": ["azithromycin", "macrolide", "alternative", "penicillin allergy", "antibiotic", "monograph"],
    },
    {
        "id": "nf-ciprofloxacin-tizanidine",
        "source": "National Drug Formulary (BD) / BNF",
        "section": "Interactions — Ciprofloxacin",
        "ref": "Ciprofloxacin + tizanidine",
        "lang": "en",
        "text": "Ciprofloxacin is contraindicated with tizanidine: it markedly increases tizanidine exposure, causing dangerous hypotension and sedation.",
        "tags": ["ciprofloxacin", "tizanidine", "interaction", "contraindicated", "hypotension"],
    },
    {
        "id": "nf-paracetamol",
        "source": "National Drug Formulary (BD) / BNF",
        "section": "Paracetamol",
        "ref": "Paracetamol — paediatric dose",
        "lang": "en",
        "text": "Paracetamol is an antipyretic and analgesic. Paediatric dose is 10 to 15 mg/kg per dose, every 4 to 6 hours, to a maximum of four doses in 24 hours.",
        "tags": ["paracetamol", "fever", "antipyretic", "dose", "paediatric", "mg/kg", "monograph"],
    },
    {
        "id": "nf-salbutamol",
        "source": "National Drug Formulary (BD) / BNF",
        "section": "Salbutamol",
        "ref": "Salbutamol — beta-2 agonist",
        "lang": "en",
        "text": "Salbutamol is a short-acting beta-2 agonist used for wheeze and asthma, delivered by inhaler or nebuliser.",
        "tags": ["salbutamol", "beta agonist", "asthma", "wheeze", "inhaler", "monograph"],
    },
    {
        "id": "patient-pneumonia-bn",
        "source": "DGHS Standard Treatment Guidelines (Bangladesh)",
        "section": "Caregiver counselling — pneumonia",
        "ref": "Pneumonia — plain language",
        "lang": "bn",
        "text": "নিউমোনিয়া হলো ফুসফুসের সংক্রমণ। গুরুতর হলে শিশু দ্রুত শ্বাস নেয় ও বুক টেনে শ্বাস নেয়; তখন দেরি না করে হাসপাতালে নিতে হয়।",
        "tags": ["নিউমোনিয়া", "pneumonia", "ফুসফুস", "শ্বাস", "বুক", "হাসপাতাল", "bangla", "caregiver"],
    },
]
